import puppeteer from 'puppeteer';
const args=['--no-sandbox','--headless=new','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--enable-gpu-rasterization','--disable-software-rasterizer','--window-size=1280,720'];
const browser=await puppeteer.launch({headless:'new',ignoreDefaultArgs:true,executablePath:'/usr/bin/google-chrome',args});
const page=await browser.newPage();
page.on('console', msg => console.log(msg.type(), msg.text()));
page.on('pageerror', err => console.log('PAGEERROR:', err.message));
await page.setViewport({width:1280,height:720});
await page.goto('http://localhost:8090/webgl_test.html',{waitUntil:'networkidle0',timeout:30000});
await new Promise(r=>setTimeout(r,1000));
await page.screenshot({path:'/tmp/webgl_test_swift.png'});
console.log('saved /tmp/webgl_test_swift.png');
await browser.close();
