import type { BiomePalette } from './types';

export const hydroDam: BiomePalette = {
  id: 'hydroDam',
  name: 'Hydro-Dam',
  description: 'Industrial concrete channel — stilling basin, vortex drain, overflow pipe',
  skyColor: '#6a7a8a',
  fogColor: '#8a9aaa',
  fogDensity: 0.025,
  fogNear: 30,
  fogFar: 180,
  waterColor: '#2a4a5a',
  waterDeepColor: '#0a2a3a',
  foamColor: '#c0d0d8',
  causticsIntensity: 0.28,
  waterOpacity: 0.9,
  flowSpeed: 1.85,
  lightTemp: 6100,
  sunColor: '#e0e8f0',
  sunIntensity: 0.92,
  ambientIntensity: 0.42,
  hemiSkyColor: '#6a7a8a',
  hemiGroundColor: '#3a3a3a',
  fillColor: '#5a6a7a',
  fillIntensity: 0.32,
  rockBaseColor: '#6a6e72',
  rockMossColor: '#3a4a3a',
  weatheringIntensity: 0.55,
  vegetationColor: '#3a4a3a',
  vegetationDensity: 0.15,
  treeDensity: 0.08,
  grassDensity: 0.12,
  wildflowerColors: ['#808080', '#607060'],
  fireflyCount: 0,
  mistDensity: 0.48,
  sunShaftIntensity: 0.22,
  fallingLeaves: false,
  ambientAudio: 'ambient-dam-001',
  transitionDuration: 3,
};
