/**
 * Typed facade for `FlowingWater.jsx`.
 *
 * WHY A FACADE INSTEAD OF A .tsx CONVERSION (issue #313, work item 3):
 * A straight `.jsx -> .tsx` rename produces 67 type errors in this file alone —
 * overwhelmingly implicit-any callback parameters and untyped `useRef()` handles
 * threaded through the per-frame uniform updates. Fixing them means touching
 * ~70 sites inside the hottest water-render path, which is exactly the kind of
 * churn that risks a silent visual regression. The brief calls for a thin typed
 * facade in that case, so the runtime module stays `.jsx` and this declaration
 * carries the contract.
 *
 * `tsconfig.typecheck.json`'s `src/**\/*.ts` include picks this file up, and TS
 * module resolution prefers it over the sibling `.jsx`, so every TypeScript
 * consumer of `../FlowingWater` is now checked against these props.
 *
 * KEEP IN SYNC with the destructured parameter list at the top of
 * `FlowingWater.jsx`. `shaderFacades.contract.test.ts` asserts the
 * runtime module still matches the shape declared here.
 */

import type * as THREE from 'three';
import type * as React from 'react';

/**
 * GPU flow-field handle produced by the heightmap flow system.
 * FlowingWater reads `flowMapTexture` and, when present, kicks `initWebGPU()`.
 */
export interface HeightmapFlowHandle {
  flowMapTexture?: THREE.Texture | null;
  initWebGPU?: () => Promise<unknown>;
  [key: string]: unknown;
}

export interface FlowingWaterProps {
  /** Water surface geometry generated by the owning track segment. */
  geometry: THREE.BufferGeometry;
  /** Base flow rate, further scaled by the biome multiplier and slushiness. */
  flowSpeed?: number;
  /** Overrides the biome's shallow water colour. */
  baseColor?: THREE.ColorRepresentation;
  /** Overrides the biome's foam colour. */
  foamColor?: THREE.ColorRepresentation;
  /** Overrides the biome's edge-highlight colour. */
  edgeHighlightColor?: THREE.ColorRepresentation;
  /** Remote shader id; falls back to the biome's shader when null. */
  shaderId?: string | null;
  /** Fired once the dynamic shader resolves (or fails). */
  onShaderLoad?: (code: string | null, error: string | null) => void;
  /** Biome key into `constants/biomes`; unknown keys fall back to `river`. */
  biome?: string;
  isNight?: boolean;
  flowMap?: THREE.Texture | null;
  heightmapFlow?: HeightmapFlowHandle | null;
  vehiclePos?: THREE.Vector3 | null;
  vehicleVelocity?: THREE.Vector3 | null;
  /** Rain/weather ripple strength, 0..1. */
  weatherRipple?: number;
  /** Weather wetness: darkens the surface and boosts reflection, 0..1. */
  wetness?: number;
  /** Glacial slush factor; also scales effective flow speed. */
  slushiness?: number;
  /** Vertical offset applied to the water surface. */
  waterSurfaceOffset?: number;
  /** World-space sun position used for the specular highlight. */
  sunWorldPosition?: THREE.Vector3 | null;
  /** Pond segments use calmer waves and a stronger specular. */
  isPond?: boolean;
  /** World-space vortex drain center for Hydro-Dam UV swirl. */
  vortexCenter?: THREE.Vector3 | null;
  /** Vortex influence radius in world units. */
  vortexRadius?: number;
  /** Swirl intensity multiplier (0 = off). */
  vortexIntensity?: number;
}

/** True when the water shader samples the planar reflection target. */
export const FLOWING_WATER_SAMPLES_REFLECTION: boolean;

declare const FlowingWater: React.FC<FlowingWaterProps>;
export default FlowingWater;
